### ISSUE TITLE
Add posibility to have empty state (no date selected)

### ISSUE THREAD

**Issue by Zaporozhec7** [weifeiyue/vue-datepicker-local#1]
This is feature request. Will be great if component allow to have empty state, e.g. no date selected, and posibility to remove date (make it empty). Because that functionality needed often, when dates optional.

Thanks very much for this library.

**Comment by weifeiyue** [comment]
@Zaporozhec7 
fix @[v1.0.3](https://github.com/weifeiyue/vue-datepicker-local/releases/tag/v1.0.3)
demo(https://weifeiyue.github.io/vue-datepicker-local/)

**Comment by Zaporozhec7** [comment]
Thank you very much!
