### ISSUE TITLE
Error while running npm run build

### ISSUE THREAD

**Issue by ThomasFerro** [weifeiyue/vue-datepicker-local#10]
Hi, 

# Issue summary 

I've found an issue when trying to build my project generated with `vue-cli`. This problem only occurs when running the `npm run build` command.

# Reproduce the issue 

- Create a new project using the command `vue init webpack test-project`;
- Install vue-datepicker-local : `npm install vue-datepicker-local -s`;
- Install the packages : `npm i`;
- In the `App.vue` component, import the component following [the official documentation](https://github.com/weifeiyue/vue-datepicker-local#es6);

You can start a development server (using `npm run dev`) and see the component working fine but the build compilation doens't work, retuning this error :

ERROR in static/js/vendor.4fff840b4e16f40a85dd.js from UglifyJs
Unexpected token: operator (>) [./node_modules/vue-datepicker-local/src/index.js:2,0][static/js/vendor.4fff840b4e16f40a85dd.js:11021,21]

# Investigations

While trying to understand the issue's origin, I've found something that bugs me in the component's `package.json`.

In this file, you declare that the main file to use is `src/index.js`, when in my opinion it should be the `dist` file.

`"main": "src/index.js",`

When I modify this attribute to put the `dist/vue-datepicker-local.js` file, the compilation works but I have to include the css myself using :
`@import '../node_modules/vue-datepicker-local/dist/vue-datepicker-local.css';` 

Thanks.

**Comment by vikramkute** [comment]
#8

**Comment by weifeiyue** [comment]
@ThomasFerro  fixed [@v1.0.8](https://github.com/weifeiyue/vue-datepicker-local/releases/tag/v1.0.8)
