### ISSUE TITLE
can't work with bootstrap

### ISSUE THREAD

**Issue by FrideCode** [weifeiyue/vue-datepicker-local#12]
I use bootstarp-vue in my project.Some confliction of style between bootstrap and the date picker. I almost can not see anything when I use them both.I hope our date picker is more compatible with bootstrap.

**Comment by denisvmedia** [comment]
You can import the code without styles this way:

```
import cDatepicker from "vue-datepicker-local/dist/vue-datepicker-local"
```

So that you can define your own styles and you will have no conflicts.

**Comment by brightertools** [comment]
I am using bootstrap 4 and it seems ok.

just added these tweaks:

```
/* vue-datepicker-local helpers */
input.localDatePicker {
    background-color: white !important;
    border: 1px solid #CED4DA !important;
}
.calendar-date-selected, .calendar-date-selected:hover {
    color: white !important;
}
```

**Comment by weifeiyue** [comment]
Thanks @denisvmedia @brightertools
