### ISSUE TITLE
Can [Feature Request] datepicker support inline mode?

### ISSUE THREAD

**Issue by antonreshetov** [weifeiyue/vue-datepicker-local#15]
It would be desirable that at a component there was also a built-in mode

`<vue-datepicker-local type="inline" />`

<img width="208" alt="2017-12-07 9 34 56" src="https://user-images.githubusercontent.com/17480987/33701905-154d1726-db32-11e7-919b-f9f70b854d01.png">

**Comment by weifeiyue** [comment]
@antonreshetov please check out the [inline demo](https://weifeiyue.github.io/vue-datepicker-local/#inlineMode)

**Comment by antonreshetov** [comment]
Wow, so fast. Thank you very much! I really have modified for myself. Now I will use the native functionality.
<img width="854" alt="2017-12-07 12 52 20" src="https://user-images.githubusercontent.com/17480987/33709320-0eb5ba46-db4e-11e7-9df9-c9ef38442d0b.png">

**Comment by weifeiyue** [comment]
Good job!:thumbsup:
