### ISSUE TITLE
Date Format with range

### ISSUE THREAD

**Issue by TartanLeGrand** [weifeiyue/vue-datepicker-local#17]
Hello,
I would like to have a model range with the date format: YYYY-MM

Do you think it's possible?

I have already tested and the result obtained is not that expected.

Thank you for your reply

**Comment by weifeiyue** [comment]
@TartanLeGrand 
```html
 <vue-datepicker-local v-model="timeRange" format="YYYY-MM" />
```
The result is still the time object，you should format it what you want

**Comment by TartanLeGrand** [comment]
@weifeiyue 

![image](https://user-images.githubusercontent.com/25587164/33834367-021c40ce-de83-11e7-817b-1ab42d791ea6.png) the result. 

I want this with only years and month: 
![image](https://user-images.githubusercontent.com/25587164/33834548-939a3894-de83-11e7-8143-bc8ba2335ddc.png)

**Comment by weifeiyue** [comment]
@TartanLeGrand 
https://jsfiddle.net/lovearcs/e8uqxzno/
This is not in line with your request?

**Comment by wangchangdong** [comment]
This plug-in whether or not to match the mobile terminal ？waiting for your  early reply，thank you

**Comment by weifeiyue** [comment]
@wangchangdong  no~

**Comment by wangchangdong** [comment]
oh my god！Recently looking for a mobile terminal one

**Comment by TartanLeGrand** [comment]
@weifeiyue Thanks for your reply.

I have one more problem with picker... is this : 

![image](https://user-images.githubusercontent.com/25587164/33983215-9afff736-e0b3-11e7-95d8-717d5911775a.png)

**Comment by weifeiyue** [comment]
@TartanLeGrand Do you cover my style? Can you reproduce this problem online?

**Comment by TartanLeGrand** [comment]
I used your style, it seems complicated to reproduce all this online.

**Comment by weifeiyue** [comment]
@TartanLeGrand I can not reproduce this problem :smile:

**Comment by TartanLeGrand** [comment]
My view: 

```js
<template>
    <vue-datepicker-local v-model="timeRange" format="YYYY-MM-DD" />
</template>

<script>
    import VueDatepickerLocal from 'vue-datepicker-local'

    export default {
        components: {
            VueDatepickerLocal
        },
        data () {
            return {
                timeRange: [new Date(), new Date()],
                 local: {
                    dow: 0, // Sunday is the first day of the week
                    hourTip: 'Select Hour', // tip of select hour
                    minuteTip: 'Select Minute', // tip of select minute
                    secondTip: 'Select Second', // tip of select second
                    yearSuffix: '', // suffix of head year
                    monthsHead: 'January_February_March_April_May_June_July_August_September_October_November_December'.split('_'), // months of head
                    months: 'Jan_Feb_Mar_Apr_May_Jun_Jul_Aug_Sep_Oct_Nov_Dec'.split('_'), // months of panel
                    weeks: 'Su_Mo_Tu_We_Th_Fr_Sa'.split('_') // weeks
            }
            }
        }
    }
</script>
```
I have import the vue-datepicker-local.css too.

**Comment by TartanLeGrand** [comment]
The problem comes from bootstrap...
