### ISSUE TITLE
 can't work with popupClass

### ISSUE THREAD

**Issue by Hihuihui** [weifeiyue/vue-datepicker-local#18]
<vue-datepicker-local v-model="date_range" range-separator="~" popupClass="width:418px;"></vue-datepicker-local>

**Comment by Hihuihui** [comment]
<vue-datepicker-local v-model="date_range" range-separator="~" popupClass="width:418px;"></vue-datepicker-local>

**Comment by weifeiyue** [comment]
Can you  show how you used it?

**Comment by Hihuihui** [comment]
`<vue-datepicker-local v-model="date_range" range-separator="~" style="min-width:210px;" popup-class="width:413px;"></vue-datepicker-local>`

**Comment by Hihuihui** [comment]
`<vue-datepicker-local v-model="date_range" range-separator="~"  popupClass="width:413px;"></vue-datepicker-local>` 

used this

**Comment by weifeiyue** [comment]
@Hihuihui should like this
```html
popup-class="custom-popup"
```
'custom-popup' is class name
