### ISSUE TITLE
Module build failed: Error: ENOENT

### ISSUE THREAD

**Issue by drkwolf** [weifeiyue/vue-datepicker-local#19]
Hi i got this error :
Error: Module build failed: Error: ENOENT: no such file or directory, open '$HOME/web/node_modules/vuejs-datepicker/dist/build.js'  at Error (native) vue.js:815:7
 
 "vue": "^2.5.9"
 "vue-datepicker-local": "^1.0.9",

**Comment by weifeiyue** [comment]
@drkwolf vuejs-datepicker is not my 'vue-datepicker-local'
