### ISSUE TITLE
How would I set a min and max?

### ISSUE THREAD

**Issue by getsetbro** [weifeiyue/vue-datepicker-local#21]
I would like to be able to limit the user to a min and a max date.

**Comment by weifeiyue** [comment]
@getsetbro use [disabledDate](https://weifeiyue.github.io/vue-datepicker-local/#disableddate)

**Comment by getsetbro** [comment]
Oh great! I did it like this
```
disabledDate(date) {
  return date < _util.minutes_ago || date > _util.year_from_now;
}
```
