### ISSUE TITLE
Select a from date into the future when using range

### ISSUE THREAD

**Issue by ja1984** [weifeiyue/vue-datepicker-local#24]
Awesome library!

Would it be possible to have an option to be able to select an from date that is later than the to date, and then have the to date update to the same date.

My use case is that I want to be able to a filter a list, and I want to be able to filter on dates in the future. Now I need to set the to date first to be able to set the from date.

I tried using the disabledDate options but that doesn't do anything.

**Comment by weifeiyue** [comment]
@ja1984  Can you show me how you did it?

**Comment by ja1984** [comment]
@weifeiyue thank you for the quick reply!

My implementation is pretty basic.

<vue-datepicker-local class="ft-datepicker" :rangeSeparator="'-'" :clearable="true" :disabledDate="()=>{return false;}" v-model="range" />

Try changing the return to true makes all dates unavailable, so I'm gussing the implementation is diffrent for this. Just to be clear, what I want to be able to do

![datepicker](https://user-images.githubusercontent.com/1274603/35210600-2fa5874e-ff53-11e7-9765-94d78bd62e30.png) is to be able to select the 25th on left hand side and then have right hand side change to the same value.

**Comment by weifeiyue** [comment]
@ja1984 You can do it like [this ](https://jsfiddle.net/lovearcs/3405dot6/)

**Comment by ja1984** [comment]
@weifeiyue The problem is still that if the 23rd is selected for the "to" calendar, I can not select a date that is further into the future in the from calendar. :(

**Comment by weifeiyue** [comment]
@ja1984 The end time must be greater than the start time
