### ISSUE TITLE
Possible to Start with Selecting the Year?

### ISSUE THREAD

**Issue by paulredmond** [weifeiyue/vue-datepicker-local#28]
I'm trying out this library on a project, great work!

I am curious is it's already possible or planned to start the date picker out in the year or month part of selection? In my case the user is picking a birthdate so starting with the year is most intuitive.

**Comment by weifeiyue** [comment]
@paulredmond [demo](https://weifeiyue.github.io/vue-datepicker-local/#year)

**Comment by paulredmond** [comment]
Hi @weifeiyue!

So I was curious if when you click the input if it would _start_ with the year first, and then it would change to the month/day selection?

So for example, this is the first thing you would see when you click the input:

![date-picker-example](https://user-images.githubusercontent.com/177773/36611755-b4ac8cce-1891-11e8-8027-22a0cfe98ea5.gif)

**Comment by weifeiyue** [comment]
@paulredmond Sorry, I do not plan to support what you said.You have to switch manually to the month selection
