### ISSUE TITLE
disabledDate

### ISSUE THREAD

**Issue by bralion** [weifeiyue/vue-datepicker-local#30]
![image](https://user-images.githubusercontent.com/12732119/37252348-9b150060-2517-11e8-93be-2e00e62061b4.png)
![image](https://user-images.githubusercontent.com/12732119/37252393-4281d3d2-2518-11e8-8075-5bbc07acb63b.png)
![image](https://user-images.githubusercontent.com/12732119/37252403-5bde5cd8-2518-11e8-858b-4e61902dc489.png)

**Comment by weifeiyue** [comment]
@bralion 你用了什么UI框架，样式被你的UI框架覆盖了

**Comment by bralion** [comment]
2017年12月是可选的；但是选择年的时候2017年是不可选的。应该不是样式覆盖的问题；因为2017标签上面有一个属性是disabled.

**Comment by bralion** [comment]
应该是不能时间段选择吧，目前已经通过其它途径解决了

**Comment by weifeiyue** [comment]
你的disabledDate 是怎么写的？

**Comment by bralion** [comment]
因为没成功所以代码没上传，现在已经找不到当时写的代码，因为我们是要求是传入一个最后日期，然后向前推三个月均可选，我当时的大概思路是
 if(time.getYear()==this.endTime.getYear()){//如果年相等
      //小于 截止时间 并且 大于 截止时间的月份 -3 则返回false  可选
     //否则返回true
}else if(time.getYear()==this.endTime.getYear()-1&&this.endTime.getMonth()<2){//如果年份等于截止时间减1并且月份小于3月
//如果this.endTime.getMonth()+12-3<  time.getMonth()   表示当前月可选， return false
//否则 return true

}

大致代码是这样。由于当时没有成功就换了一种方式来实现。所以现在也找不到原始代码

**Comment by weifeiyue** [comment]
这个问题的确比较麻烦，disabledDate多加了一个format参数用来做判断，可以查看  [demo](https://jsfiddle.net/lovearcs/c72gwnL1/2/)

**Comment by bralion** [comment]
好的，谢谢
