### ISSUE TITLE
How to set placeholder title?

### ISSUE THREAD

**Issue by alexTitakoff** [weifeiyue/vue-datepicker-local#32]
Hello!

So nice component!

Tell me please, can I set a placeholder title before choosing a date?

**Comment by weifeiyue** [comment]
Thanks! In fact, it is supported. I forgot to write it into the document.
```html
<vue-datepicker-local placeholder="select date"/>
```

**Comment by alexTitakoff** [comment]
OMG  🤣🤣

thanks 👍🏻 

I don't find this property in the documentation.

**Comment by weifeiyue** [comment]
[The doc is updated now](https://github.com/weifeiyue/vue-datepicker-local#props)
