### ISSUE TITLE
最大最小可选时间 Max and Min Time can choose

### ISSUE THREAD

**Issue by fighthorse** [weifeiyue/vue-datepicker-local#44]
怎么去加属性，现在时间可选范围呢？
how to add props to limit the time while can to choose by user.

插件现在还在持续优化么？
this projects is still refreshing？

**Comment by fighthorse** [comment]
限制可选 星期 ,例如不能选择 星期天。
Limit weekday ，example can't choose sunday .

**Comment by weifeiyue** [comment]
看这个例子就行了[demo](https://weifeiyue.github.io/vue-datepicker-local/#disableddate)
