### ISSUE TITLE
Second calendar appears below first calendar when used with bootstrap-vue.

### ISSUE THREAD

**Issue by hifall** [weifeiyue/vue-datepicker-local#46]
When I use this plugin inside bootstrap-vue (https://bootstrap-vue.js.org/) in range mode:

`<vue-datepicker-local v-model="range"></vue-datepicker-local>`

the second calendar appears below the first one, instead of to the right of it.

It appears that .datepicker-popup has a width of 403px, which is too narrow for 2 .calendar side by side.

I think some style might be messed up by bootstrap-vue.

Thanks in advance!

**Comment by weifeiyue** [comment]
you should use style to fix it, thanks
