### ISSUE TITLE
Plugin in range mode not responsive.

### ISSUE THREAD

**Issue by hifall** [weifeiyue/vue-datepicker-local#47]
Use the plugin in range mode, and minimize the window width, one can see that part of the plugin is hidden.

One can reproduce this behavior by:
1 navigate to: https://weifeiyue.github.io/vue-datepicker-local/;
2 click the datepicker in range mode;
3 minimize window width;
4 now part of the plugin dropdown is hidden.

I think in this scenario, the second calendar should be pushed down, so that it becomes fully visible again.

**Comment by weifeiyue** [comment]
Sorry, responsive not supported
