### ISSUE TITLE
How to enable future dates for start date?

### ISSUE THREAD

**Issue by seanodotcom** [weifeiyue/vue-datepicker-local#57]
After initial user testing of my app using your (great) Vue.js plugin, every one of the users mentioned that the datepicker, using a range of dates, was broken/not working properly.

They said this because they every start date in the future is disabled, and cannot be selected.

While I understand needing to ensure that the end date > start date, this restriction is confusing to many people on the UI side who would never "think" to select an end date first when entering in arrival/departure times for flights, vacation start/end dates (my use), etc.

How can this be resolved, allowing for full range selection ability?

**Comment by weifeiyue** [comment]
good idea~, i have resolved this problem [@v1.0.16](https://github.com/weifeiyue/vue-datepicker-local/releases/tag/v1.0.16)

**Comment by seanodotcom** [comment]
Works great. Thanks for the prompt response!

**Comment by weifeiyue** [comment]
@seanodotcom sorry, v1.0.16 has a bug，it was fixed @v1.0.17
