### ISSUE TITLE
Not sure how to import vue-datepicker-local

### ISSUE THREAD

**Issue by timothyylim** [weifeiyue/vue-datepicker-local#58]
I am getting an error when trying to build vue-datepicker-local using the vue-cli template:

`ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

Would anyone have any tips on how to do it properly? 

I've created a more detailed question here:

https://stackoverflow.com/questions/51580272/vue-parseerror-import-and-export-may-appear-only-with-sourcetype-module

Thank you very much.

**Comment by weifeiyue** [comment]
fixed @1.0.18
