### ISSUE TITLE
Time picker can hide minutes and hours

### ISSUE THREAD

**Issue by kps1ny** [weifeiyue/vue-datepicker-local#60]
Thanks for this useful Vue code!

Is there a way for the time picker to hide the minutes and seconds? I would like users to be able to pick an hour but not minutes and seconds for their input. (The minutes and seconds would be hidden in both the input field and in the selection interface.) As a bonus, the hours would show zeros for minutes, as in 0000 or 0900 or 2200.

Thanks for your consideration,
-Ken

**Comment by weifeiyue** [comment]
sorry, there is not plan to do it. Thanks for your feedback
