### ISSUE TITLE
The month shown is over one than the month select（for example: if you select June , but it will show July in UI ）

### ISSUE THREAD

**Issue by hkaikai** [weifeiyue/vue-datepicker-local#62]
`<vue-datepicker-local v-model="value" format="YYYY-MM" :disabled-date="disabledDate" clearable />`

`data() { return { value: new Date() } }`

`methods: { disabledDate() { return false } }`

The month shown is over one than the month select（for example: if you select June , but it will show July in UI ）
@weifeiyue 我这里这样写可以100%复现这个问题，你可以帮我看一下嘛，谢谢

把系统时间调到月底后有这个问题

**Comment by weifeiyue** [comment]
bug fixed @v1.0.19
