### ISSUE TITLE
有空能不能加一个年月日 时分的啊   这个也是有需求的

### ISSUE THREAD

**Issue by wangsonghui** [weifeiyue/vue-datepicker-local#65]
有空能不能加一个年月日 时分的啊   这个也是有需求的
有空能不能加一个年月日 时分的啊   这个也是有需求的
有空能不能加一个年月日 时分的啊   这个也是有需求的

**Comment by weifeiyue** [comment]
[https://weifeiyue.github.io/vue-datepicker-local/#time](https://weifeiyue.github.io/vue-datepicker-local/#time)
这个没有达到需求？

**Comment by zhujinhu21** [comment]
@weifeiyue 你的这个时间不能选择
