### ISSUE TITLE
disabled dates from current

### ISSUE THREAD

**Issue by JohnAragon** [weifeiyue/vue-datepicker-local#79]
How to disable the dates less than the current date?

**Comment by yuvipatel** [comment]
How to disable the years less than current years? It's similar to what @JohnAragon asked the only difference is if date picker only shows years. How to go about that.

**Comment by JohnAragon** [comment]
@yuvipatel 
try this: 
disabledDate (time) {
        return time.getTime() < new Date().getTime();
 },
