### ISSUE TITLE
Allowing keyboard navigation

### ISSUE THREAD

**Issue by ThomasFerro** [weifeiyue/vue-datepicker-local#9]
Hi,

Thanks for the work on this component, it's astonishingly easy to import and use and it works perfectly well.

However, I found one particular case where the datepicker isn't really efficient : when you try to make it fit into a form with tab navigation.

I was expecting to have the possibility to modify the selected date with the keys, just like you can do in [the default date input](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/date). 

I think it's more of a feature request than really an issue but I havn't found a more suitable place to do this request.

Again, it's just an edge case, the component works like a charm :)

**Comment by Arsini** [comment]
IE don't working.

**Comment by ThomasFerro** [comment]
I've made a date input mask (using [Moment.js](https://momentjs.com/)), do you think that it's worth implementing in your project @weifeiyue ?

Here's the component : https://jsfiddle.net/ThomasFerro/bxv698vw/
